import { ChallengeDetails, shapeIds } from 'renderer/state/types';
import square2a from 'renderer/assets/challenges/Square_2_a.png';
import square2b from 'renderer/assets/challenges/Square_2_b.png';
import square2c from 'renderer/assets/challenges/Square_2_c.png';
import square2d from 'renderer/assets/challenges/Square_2_d.png';
import circle2b from 'renderer/assets/challenges/Circle_2_b.png';
import circle2a from 'renderer/assets/challenges/Circle_2_a.png';
import diamond2a from 'renderer/assets/challenges/Diamond_2_a.png';
import diamond2b from 'renderer/assets/challenges/Diamond_2_b.png';
import triangle2a from 'renderer/assets/challenges/Triangle_2_a.png';
import triangle2b from 'renderer/assets/challenges/Triangle_2_b.png';



export type challengeDetailsMap = Record<shapeIds, ChallengeDetails>;
export const challenges: challengeDetailsMap = {
  Circle_2_a: {
    shape: 'circle',
    numCells: 2,
    letter: 'a',
    difficulty: 'easy',
    imageUrl: circle2a,
  },
  Circle_2_b: {
    shape: 'circle',
    numCells: 2,
    letter: 'b',
    difficulty: 'easy',
    imageUrl: circle2b,
  },
  Circle_2_c: {
    shape: 'circle',
    numCells: 2,
    letter: 'c',
    difficulty: 'medium',
    imageUrl: 'Circle_2_c.png',
  },
  Circle_2_d: {
    shape: 'circle',
    numCells: 2,
    letter: 'd',
    difficulty: 'medium',
    imageUrl: 'Circle_2_d.png',
  },
  Circle_2_e: {
    shape: 'circle',
    numCells: 2,
    letter: 'e',
    difficulty: 'medium',
    imageUrl: 'Circle_2_e.png',
  },
  Circle_2_f: {
    shape: 'circle',
    numCells: 2,
    letter: 'f',
    difficulty: 'medium',
    imageUrl: 'Circle_2_f.png',
  },
  Square_2_a: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'easy',
    imageUrl: square2a,
  },
  Square_2_b: {
    shape: 'square',
    numCells: 2,
    letter: 'b',
    difficulty: 'easy',
    imageUrl: square2b,
  },
  Square_2_c: {
    shape: 'square',
    numCells: 2,
    letter: 'c',
    difficulty: 'easy',
    imageUrl: square2c,
  },
  Square_2_d: {
    shape: 'square',
    numCells: 2,
    letter: 'd',
    difficulty: 'easy',
    imageUrl: square2d,
  },
  Square_2_e: {
    shape: 'square',
    numCells: 2,
    letter: 'e',
    difficulty: 'medium',
    imageUrl: 'Square_2_e.png',
  },
  Square_2_f: {
    shape: 'square',
    numCells: 2,
    letter: 'f',
    difficulty: 'medium',
    imageUrl: '',
  },
  Triangle_2_a: {
    shape: 'triangle',
    numCells: 2,
    letter: 'a',
    difficulty: 'easy',
    imageUrl: triangle2a,
  },
  Triangle_2_b: {
    shape: 'triangle',
    numCells: 2,
    letter: 'b',
    difficulty: 'easy',
    imageUrl: triangle2b,
  },
  Triangle_2_c: {
    shape: 'triangle',
    numCells: 2,
    letter: 'c',
    difficulty: 'medium',
    imageUrl: 'Triangle_2_c.png',
  },

  Diamond_2_a: {
    shape: 'diamond',
    numCells: 2,
    letter: 'a',
    difficulty: 'easy',
    imageUrl: diamond2a,
  },
  Diamond_2_b: {
    shape: 'diamond',
    numCells: 2,
    letter: 'b',
    difficulty: 'easy',
    imageUrl: diamond2b,
  },
  Diamond_2_c: {
    shape: 'diamond',
    numCells: 2,
    letter: 'c',
    difficulty: 'medium',
    imageUrl: 'Diamond_2_c.png',
  },
  Diamond_2_d: {
    shape: 'diamond',
    numCells: 2,
    letter: 'd',
    difficulty: 'medium',
    imageUrl: 'Diamond_2_d.png',
  },
  Diamond_2_f: {
    shape: 'diamond',
    numCells: 2,
    letter: 'f',
    difficulty: 'hard',
    imageUrl: 'Diamond_2_f.png',
  },
  Diamond_2_g: {
    shape: 'diamond',
    numCells: 2,
    letter: 'a',
    difficulty: 'easy',
    imageUrl: 'Diamond_2_g.png',
  },
  Circle_3_a: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Circle_3_b: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Circle_3_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Circle_4_a: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Circle_4_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Circle_4_g: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Circle_6_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Circle_6_g: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Circle_8_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Circle_9_g: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_3_a: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_3_b: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_4_a: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_4_b: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_4_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_4_d: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_4_e: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_4_g: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_4_h: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_6_a: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_6_b: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_8_a: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_8_b: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_8_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_8_e: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_8_g: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_8_h: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_8_i: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_8_j: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Square_9_a: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Triangle_3_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Triangle_3_d: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Triangle_3_e: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Triangle_3_f: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Triangle_4_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Triangle_4_d: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Triangle_4_e: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Triangle_6_d: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Triangle_8_d: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Triangle_8_e: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Triangle_9_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_3_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_3_d: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_4_a: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_4_b: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_4_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_4_d: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_4_f: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_4_g: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_4_h: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_6_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_6_d: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_8_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_8_d: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_8_e: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_8_f: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_8_g: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_8_h: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_8_i: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_8_j: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
  Diamond_9_c: {
    shape: 'square',
    numCells: 2,
    letter: 'a',
    difficulty: 'hard',
    imageUrl: '',
  },
};

export const tom = 'tom';
